import { useEffect, useMemo, useState } from 'react';
import { collection, doc, onSnapshot, runTransaction, serverTimestamp, setDoc } from 'firebase/firestore';
import { CheckCircle2, Clock3, FileText, Gift, KeyRound, Minus, Plus, ReceiptText, Save, Search, Settings2, Users, WalletCards, X } from 'lucide-react';
import { db } from '../../lib/firebase';
import { grantWalletRewardForCompletedOrder, isCompletedOrderStatus } from '../../lib/walletRewards';

const toMillis = (v) => v?.toMillis?.() || (v?.seconds ? v.seconds * 1000 : new Date(v || 0).getTime() || 0);
const money = (v) => Number(v || 0).toLocaleString('en-US');
const customer = (o) => o.formData?.name || o.customer?.name || o.customerName || o.name || 'عميل المتجر';
const phone = (o) => o.formData?.fullPhone || o.formData?.phone || o.customer?.phone || o.phone || '---';
const dateText = (v) => { const d = v?.toDate?.() || new Date(v || Date.now()); return Number.isNaN(d.getTime()) ? '---' : new Intl.DateTimeFormat('ar-YE', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(d); };

const WalletView = () => {
    const [wallets, setWallets] = useState([]);
    const [orders, setOrders] = useState([]);
    const [transactions, setTransactions] = useState([]);
    const [settings, setSettings] = useState({ defaultReward: 500, enabled: true });
    const [tab, setTab] = useState('overview');
    const [search, setSearch] = useState('');
    const [editingWallet, setEditingWallet] = useState(null);
    const [adjustment, setAdjustment] = useState({ type: 'credit', amount: '', note: '' });
    const [rewarding, setRewarding] = useState('');
    const [saving, setSaving] = useState(false);
    const [notice, setNotice] = useState('');

    useEffect(() => {
        const stops = [
            onSnapshot(collection(db, 'customer_wallets'), snap => setWallets(snap.docs.map(d => ({ id: d.id, ...d.data() })).sort((a, b) => Number(b.balance || 0) - Number(a.balance || 0)))),
            onSnapshot(collection(db, 'orders'), snap => setOrders(snap.docs.map(d => ({ id: d.id, ...d.data() })).sort((a, b) => toMillis(b.createdAt || b.timestamp) - toMillis(a.createdAt || a.timestamp)))),
            onSnapshot(collection(db, 'wallet_transactions'), snap => setTransactions(snap.docs.map(d => ({ id: d.id, ...d.data() })).sort((a, b) => toMillis(b.createdAt) - toMillis(a.createdAt)))),
            onSnapshot(doc(db, 'settings', 'wallet'), snap => { if (snap.exists()) setSettings(prev => ({ ...prev, ...snap.data() })); })
        ];
        return () => stops.forEach(stop => stop());
    }, []);

    const walletMap = useMemo(() => new Map(wallets.map(w => [w.walletId || w.id, w])), [wallets]);
    const totalBalance = wallets.reduce((sum, w) => sum + Number(w.balance || 0), 0);
    const rewardsTotal = transactions.filter(t => t.type === 'reward').reduce((sum, t) => sum + Number(t.amount || 0), 0);
    const completed = orders.filter(o => isCompletedOrderStatus(o.status));
    const pendingRewards = completed.filter(o => o.customerWalletId && !o.walletRewardGranted);
    const filteredWallets = wallets.filter(w => `${w.customerName || ''} ${w.phone || ''} ${w.walletId || w.id}`.toLowerCase().includes(search.toLowerCase().trim()));

    const saveSettings = async () => {
        setSaving(true);
        try { await setDoc(doc(db, 'settings', 'wallet'), { defaultReward: Math.max(0, Number(settings.defaultReward || 0)), enabled: settings.enabled !== false, updatedAt: serverTimestamp() }, { merge: true }); setNotice('تم حفظ إعدادات مكافأة المحفظة.'); }
        catch (err) { console.error(err); setNotice('تعذّر حفظ إعدادات المحفظة.'); }
        finally { setSaving(false); }
    };
    const award = async (order) => {
        setRewarding(order.id);
        try { const result = await grantWalletRewardForCompletedOrder(order.id); setNotice(result.granted ? `تم إيداع $ ${money(result.amount)} للعميل.` : 'المكافأة أودعت مسبقًا أو لا يمكن إيداعها الآن.'); }
        catch (err) { console.error(err); setNotice('تعذّر إيداع المكافأة.'); }
        finally { setRewarding(''); }
    };
    const adjustWallet = async () => {
        const amount = Math.max(0, Number(adjustment.amount || 0));
        if (!editingWallet || !amount) { setNotice('أدخل مبلغًا صحيحًا.'); return; }
        const walletRef = doc(db, 'customer_wallets', editingWallet.id);
        const movementRef = doc(collection(db, 'wallet_transactions'));
        try {
            await runTransaction(db, async trx => {
                const snap = await trx.get(walletRef);
                const current = snap.exists() ? snap.data() : editingWallet;
                const oldBalance = Number(current.balance || 0);
                const debit = adjustment.type === 'debit';
                if (debit && oldBalance < amount) throw new Error('LOW_BALANCE');
                const balance = debit ? oldBalance - amount : oldBalance + amount;
                trx.set(walletRef, { ...current, walletId: current.walletId || editingWallet.id, balance, updatedAt: serverTimestamp() }, { merge: true });
                trx.set(movementRef, { walletId: current.walletId || editingWallet.id, type: adjustment.type, amount, customerName: current.customerName || '', phone: current.phone || '', note: adjustment.note.trim(), source: 'admin-wallet', createdAt: serverTimestamp() });
            });
            setNotice(adjustment.type === 'debit' ? 'تم خصم الرصيد بنجاح.' : 'تمت إضافة الرصيد بنجاح.');
            setEditingWallet(null); setAdjustment({ type: 'credit', amount: '', note: '' });
        } catch (err) { setNotice(err.message === 'LOW_BALANCE' ? 'الرصيد الحالي لا يكفي للخصم.' : 'تعذّر تنفيذ عملية المحفظة.'); }
    };
    const tabs = [['overview', 'نظرة عامة'], ['customers', 'محافظ العملاء'], ['invoices', 'فواتير ومكافآت'], ['transactions', 'سجل الحركات'], ['settings', 'الإعدادات']];
    const tabClass = id => `rounded-xl px-3 py-2 text-xs font-black transition ${tab === id ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/25' : 'bg-slate-100 text-slate-500 hover:bg-slate-200 dark:bg-white/5 dark:text-slate-300 dark:hover:bg-white/10'}`;

    return <div dir="rtl" className="mx-auto max-w-7xl space-y-5 font-['Cairo']">
        <header className="overflow-hidden rounded-[28px] border border-emerald-300 bg-gradient-to-l from-emerald-700 via-emerald-600 to-teal-500 p-6 text-white shadow-xl shadow-emerald-500/20"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div className="text-right"><div className="flex items-center gap-2"><span className="rounded-xl bg-white/15 p-2"><WalletCards size={23}/></span><h1 className="text-xl font-black md:text-2xl">قسم المحفظة والفواتير</h1></div><p className="mt-2 max-w-2xl text-xs font-bold leading-6 text-white/80">إدارة أرصدة العملاء، مكافآت الطلبات المكتملة، وسجل الإيداع والخصم المرتبط بجهاز كل عميل.</p></div><div className="rounded-2xl border border-white/25 bg-white/10 px-5 py-3 text-center backdrop-blur"><p className="text-[10px] font-black text-white/75">إجمالي أرصدة العملاء</p><p dir="ltr" className="mt-1 font-mono text-2xl font-black">$ {money(totalBalance)}</p></div></div></header>
        <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat icon={<Users size={19}/>} tone="emerald" label="محافظ العملاء" value={wallets.length}/><Stat icon={<Gift size={19}/>} tone="violet" label="مكافآت مودعة" value={`$ ${money(rewardsTotal)}`}/><Stat icon={<FileText size={19}/>} tone="blue" label="طلبات مكتملة" value={completed.length}/><Stat icon={<Clock3 size={19}/>} tone="orange" label="مكافآت بانتظار الإيداع" value={pendingRewards.length}/></div>
        <nav className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-2 shadow-sm dark:border-white/10 dark:bg-[#1a1d23]">{tabs.map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={tabClass(id)}>{label}</button>)}</nav>
        {tab === 'overview' && <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#1a1d23]"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-black"><Gift size={18} className="text-violet-500"/> مكافأة تلقائية للطلب المكتمل</h2><Badge tone={settings.enabled !== false ? 'emerald' : 'rose'}>{settings.enabled !== false ? 'مفعّلة' : 'متوقفة'}</Badge></div><p className="text-xs font-bold leading-6 text-slate-500 dark:text-slate-300">عند تغيير حالة طلب متجر مرتبط بمحفظة إلى مكتمل، يُودع الرصيد تلقائيًا مرة واحدة فقط.</p><div className="mt-4 flex justify-between rounded-xl bg-violet-50 p-3 dark:bg-violet-400/10"><span className="text-xs font-black">قيمة المكافأة الحالية</span><span dir="ltr" className="font-mono text-lg font-black text-violet-600 dark:text-violet-300">$ {money(settings.defaultReward)}</span></div><button onClick={() => setTab('settings')} className="mt-3 text-xs font-black text-emerald-600 dark:text-emerald-300">تعديل المكافأة ←</button></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#1a1d23]"><div className="mb-3 flex justify-between"><h2 className="flex items-center gap-2 font-black"><Clock3 size={18} className="text-orange-500"/> مكافآت معلقة</h2><button onClick={() => setTab('invoices')} className="text-[10px] font-black text-emerald-600">عرض الكل</button></div>{pendingRewards.slice(0, 4).map(o => <RewardRow key={o.id} order={o} loading={rewarding === o.id} onAward={award}/>) }{!pendingRewards.length && <Empty text="لا توجد مكافآت بانتظار الإيداع."/>}</section></div>}
        {tab === 'customers' && <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-[#1a1d23]"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="flex items-center gap-2 font-black"><Users size={18} className="text-emerald-500"/> إدارة محافظ العملاء</h2><div className="relative w-full sm:w-80"><Search size={15} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="ابحث بالاسم أو رقم الهاتف..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pr-9 pl-3 text-right text-xs font-bold outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-white/5"/></div></div><div className="space-y-2">{filteredWallets.map(w => <article key={w.id} className="grid gap-3 rounded-xl border border-slate-100 p-3 dark:border-white/5 md:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-black">{w.customerName || 'عميل المتجر'}</p><p dir="ltr" className="mt-1 font-mono text-[11px] font-bold text-slate-400">{w.phone || 'بدون رقم هاتف'}</p><Badge tone="slate"><KeyRound size={11}/>{w.pinConfigured ? 'PIN محمي' : 'بانتظار PIN'}</Badge></div><div dir="ltr" className="self-center text-center"><p className="text-[9px] font-bold text-slate-400">الرصيد</p><p className="font-mono text-lg font-black text-emerald-600 dark:text-emerald-300">$ {money(w.balance)}</p></div><div className="flex items-center justify-end gap-2"><button onClick={() => { setEditingWallet(w); setAdjustment({ type: 'credit', amount: '', note: '' }); }} className="inline-flex items-center gap-1 rounded-lg bg-emerald-100 px-2.5 py-2 text-[10px] font-black text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-200"><Plus size={13}/> إضافة</button><button onClick={() => { setEditingWallet(w); setAdjustment({ type: 'debit', amount: '', note: '' }); }} className="inline-flex items-center gap-1 rounded-lg bg-rose-100 px-2.5 py-2 text-[10px] font-black text-rose-700 dark:bg-rose-400/15 dark:text-rose-200"><Minus size={13}/> خصم</button></div></article>)}{!filteredWallets.length && <Empty text="لا توجد محافظ مطابقة."/>}</div></section>}
        {tab === 'invoices' && <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-[#1a1d23]"><div className="mb-4 flex justify-between"><h2 className="flex items-center gap-2 font-black"><ReceiptText size={18} className="text-blue-500"/> فواتير ومكافآت العملاء</h2><span className="text-[10px] font-bold text-slate-400">طلبات مرتبطة بمحفظة الجهاز</span></div><div className="space-y-2">{orders.filter(o => o.customerWalletId).map(o => <InvoiceRow key={o.id} order={o} wallet={walletMap.get(o.customerWalletId)} loading={rewarding === o.id} onAward={award}/>) }{!orders.filter(o => o.customerWalletId).length && <Empty text="لا توجد فواتير مرتبطة بمحافظ العملاء."/>}</div></section>}
        {tab === 'transactions' && <TransactionTable transactions={transactions}/>} 
        {tab === 'settings' && <section className="max-w-2xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#1a1d23]"><div className="mb-5 flex items-center gap-2"><Settings2 size={19} className="text-emerald-500"/><div><h2 className="font-black">إعدادات مكافأة المحفظة</h2><p className="text-[10px] font-bold text-slate-400">تطبق على الطلب المكتمل المرتبط بمحفظة العميل.</p></div></div><label className="flex items-center justify-between rounded-xl border border-slate-200 p-3 dark:border-white/10"><div><p className="text-xs font-black">تفعيل الإيداع التلقائي</p><p className="mt-0.5 text-[9px] font-bold text-slate-400">الإيداع يتم مرة واحدة فقط عند اكتمال الطلب.</p></div><input type="checkbox" checked={settings.enabled !== false} onChange={e => setSettings(p => ({ ...p, enabled: e.target.checked }))} className="h-5 w-5 accent-emerald-500"/></label><label className="mt-4 block text-xs font-black">قيمة المكافأة لكل طلب مكتمل<div className="relative mt-2"><span className="absolute left-3 top-1/2 -translate-y-1/2 font-mono text-emerald-600">$</span><input dir="ltr" value={settings.defaultReward} onChange={e => setSettings(p => ({ ...p, defaultReward: e.target.value.replace(/[^0-9.]/g, '') }))} inputMode="decimal" className="w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-center font-mono text-lg font-black outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-white/5"/></div></label><button disabled={saving} onClick={saveSettings} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-3 text-xs font-black text-white shadow-lg disabled:opacity-60"><Save size={16}/>{saving ? 'جاري الحفظ...' : 'حفظ الإعدادات'}</button></section>}
        {notice && <div className="fixed bottom-5 left-1/2 z-[150] -translate-x-1/2 rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-xs font-black text-emerald-700 shadow-xl dark:border-emerald-400/40 dark:bg-[#183127] dark:text-emerald-200">{notice}</div>}
        {editingWallet && <AdjustmentModal wallet={editingWallet} adjustment={adjustment} setAdjustment={setAdjustment} onClose={() => setEditingWallet(null)} onSave={adjustWallet}/>} 
    </div>;
};

const Stat = ({ icon, tone, label, value }) => <div className={`rounded-2xl border p-4 ${tone === 'emerald' ? 'border-emerald-200 bg-emerald-50 dark:border-emerald-400/25 dark:bg-emerald-400/10 text-emerald-600 dark:text-emerald-300' : tone === 'violet' ? 'border-violet-200 bg-violet-50 dark:border-violet-400/25 dark:bg-violet-400/10 text-violet-600 dark:text-violet-300' : tone === 'blue' ? 'border-blue-200 bg-blue-50 dark:border-blue-400/25 dark:bg-blue-400/10 text-blue-600 dark:text-blue-300' : 'border-orange-200 bg-orange-50 dark:border-orange-400/25 dark:bg-orange-400/10 text-orange-600 dark:text-orange-300'}`}>{icon}<p className="mt-2 text-[10px] font-bold text-slate-500 dark:text-slate-300">{label}</p><p className="mt-1 font-mono text-xl font-black">{value}</p></div>;
const Badge = ({ tone = 'slate', children }) => <span className={`mt-2 inline-flex items-center gap-1 rounded-md px-2 py-1 text-[9px] font-black ${tone === 'emerald' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-200' : tone === 'rose' ? 'bg-rose-100 text-rose-700 dark:bg-rose-400/15 dark:text-rose-200' : 'bg-slate-100 text-slate-500 dark:bg-white/5 dark:text-slate-300'}`}>{children}</span>;
const Empty = ({ text }) => <p className="py-10 text-center text-xs font-bold text-slate-400">{text}</p>;
const RewardRow = ({ order, loading, onAward }) => <div className="mb-2 flex items-center justify-between rounded-xl border border-slate-100 p-3 dark:border-white/5"><button disabled={loading} onClick={() => onAward(order)} className="rounded-lg bg-emerald-500 px-2.5 py-1.5 text-[10px] font-black text-white disabled:opacity-50">{loading ? 'جاري...' : 'إيداع الآن'}</button><div className="text-right"><p className="text-xs font-black">{customer(order)}</p><p className="font-mono text-[10px] text-slate-400">{order.orderId || order.id}</p></div></div>;
const InvoiceRow = ({ order, wallet, loading, onAward }) => { const complete = isCompletedOrderStatus(order.status); return <article className="grid gap-3 rounded-xl border border-slate-100 p-3 dark:border-white/5 md:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-black">{customer(order)}</p><p className="mt-1 text-[10px] font-bold text-slate-400">{order.orderId || order.id} · {dateText(order.createdAt || order.date)}</p><p dir="ltr" className="mt-1 font-mono text-[11px] font-bold text-emerald-600 dark:text-emerald-300">$ {money(wallet?.balance || 0)} wallet balance</p></div><div className="self-center"><Badge tone={complete ? 'emerald' : 'slate'}>{complete ? 'الطلب مكتمل' : 'قيد التنفيذ'}</Badge></div><div className="flex items-center justify-end">{order.walletRewardGranted ? <span className="inline-flex items-center gap-1 rounded-lg bg-violet-100 px-2.5 py-2 text-[10px] font-black text-violet-700 dark:bg-violet-400/15 dark:text-violet-200"><CheckCircle2 size={13}/> أودعت $ {money(order.walletRewardAmount)}</span> : <button disabled={!complete || loading} onClick={() => onAward(order)} className="rounded-lg bg-emerald-500 px-3 py-2 text-[10px] font-black text-white disabled:opacity-40">{loading ? 'جاري...' : 'إيداع المكافأة'}</button>}</div></article>; };
const TransactionTable = ({ transactions }) => <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-[#1a1d23]"><div className="border-b border-slate-100 p-4 dark:border-white/10"><h2 className="flex items-center gap-2 font-black"><Clock3 size={18} className="text-blue-500"/> سجل حركات المحافظ</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-xs"><thead className="bg-slate-50 text-slate-500 dark:bg-white/5 dark:text-slate-300"><tr><th className="p-3">العملية</th><th className="p-3">العميل</th><th className="p-3">الفاتورة / الملاحظة</th><th className="p-3">المبلغ</th><th className="p-3">التاريخ</th></tr></thead><tbody>{transactions.map(t => { const plus = ['reward', 'credit', 'bonus'].includes(t.type); const label = { reward: 'مكافأة مكتمل', credit: 'إضافة رصيد', bonus: 'رصيد تشجيعي', debit: 'خصم رصيد', spend: 'استخدام في شراء' }[t.type] || 'حركة محفظة'; return <tr key={t.id} className="border-t border-slate-100 dark:border-white/5"><td className="p-3 font-black">{label}</td><td className="p-3"><p className="font-bold">{t.customerName || 'عميل المتجر'}</p><p dir="ltr" className="mt-0.5 font-mono text-[9px] text-slate-400">{t.phone || ''}</p></td><td className="p-3 font-mono text-[10px] text-slate-500">{t.orderId || t.note || '---'}</td><td dir="ltr" className={`p-3 font-mono font-black ${plus ? 'text-emerald-600 dark:text-emerald-300' : 'text-rose-500 dark:text-rose-300'}`}>{plus ? '+' : '-'} $ {money(t.amount)}</td><td className="p-3 text-slate-400">{dateText(t.createdAt)}</td></tr>; })}</tbody></table>{!transactions.length && <Empty text="لا توجد حركات محفظة بعد."/>}</div></section>;
const AdjustmentModal = ({ wallet, adjustment, setAdjustment, onClose, onSave }) => <div className="fixed inset-0 z-[160] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl dark:bg-[#1a1d23]"><div className="flex items-start justify-between"><button onClick={onClose} className="text-slate-400"><X size={20}/></button><div className="text-right"><h3 className="font-black">{adjustment.type === 'debit' ? 'خصم رصيد من المحفظة' : 'إضافة رصيد إلى المحفظة'}</h3><p className="mt-1 text-[10px] font-bold text-slate-400">{wallet.customerName || 'عميل المتجر'} · الرصيد: <span dir="ltr" className="font-mono">$ {money(wallet.balance)}</span></p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => setAdjustment(p => ({ ...p, type: 'credit' }))} className={`rounded-xl py-2 text-xs font-black ${adjustment.type === 'credit' ? 'bg-emerald-500 text-white' : 'bg-slate-100 text-slate-500 dark:bg-white/5'}`}>إضافة رصيد</button><button onClick={() => setAdjustment(p => ({ ...p, type: 'debit' }))} className={`rounded-xl py-2 text-xs font-black ${adjustment.type === 'debit' ? 'bg-rose-500 text-white' : 'bg-slate-100 text-slate-500 dark:bg-white/5'}`}>خصم رصيد</button></div><input dir="ltr" value={adjustment.amount} onChange={e => setAdjustment(p => ({ ...p, amount: e.target.value.replace(/[^0-9.]/g, '') }))} inputMode="decimal" placeholder="المبلغ بالدولار" className="mt-3 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-center font-mono font-black outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-white/5"/><input value={adjustment.note} onChange={e => setAdjustment(p => ({ ...p, note: e.target.value }))} placeholder="ملاحظة اختيارية" className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-right text-xs font-bold outline-none focus:border-emerald-400 dark:border-white/10 dark:bg-white/5"/><button onClick={onSave} className={`mt-4 w-full rounded-xl py-3 text-xs font-black text-white ${adjustment.type === 'debit' ? 'bg-rose-500' : 'bg-emerald-500'}`}>تأكيد العملية</button></div></div>;

export default WalletView;
